/*******************************************************************************
 * Copyright 2016 Pitney Bowes Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License.
 *   You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an
 *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  
 *  See the License for the specific language governing permissions and limitations under the License.
 *******************************************************************************/

package com.pb.locationintelligence.common.model;

public class Match {
	/**
	 * Provides the percentage overlap of the geocode to the Place polygon layer.
	 * The returned percentage value describes the probability that the point falls in the specified Place.
	 */
    private String confidence;
    private String percentGeocode;
    
    /**
     * A code describing the precision of the geocode. One of the following:
			0:	No coordinate information is available for this candidate address.
			1:	Interpolated street address.
			2:	Street segment midpoint.
			3:	Postal code 1 centroid.
			4:	Partial postal code 2 centroid.
			5:	Postal code 2 centroid.
			6:	Intersection.
			7:	Point of interest. (If database contains POI data.)
			8:	State/province centroid.
			9:	County centroid.
			10:	City centroid.
			11:	Locality centroid.
			12-15:	Reserved for unspecified custom items.
			16:	The result is an address point.
			17:	The result was generated by using address point data to modify the candidate's segment data.
			18:	The result is an address point that was projected using the centerline offset feature. 
			You must have both a point and a street range database to use the centerline offset feature.
     */
    private String precisionLevel;
    
    /**
     * Indicates the accuracy (quality) of the assigned geocode.
     */
    private String locationCode;
    
    /**
     * Indicates the parts of the address that matched to the directory file.
     */
    private String matchCode;
   
    public String getConfidence() {
        return confidence;
    }

    public void setConfidence(String confidence) {
        this.confidence = confidence;
    }

    public String getPercentGeocode() {
        return percentGeocode;
    }

    public void setPercentGeocode(String percentGeocode) {
        this.percentGeocode = percentGeocode;
    }

    public String getLocationCode() {
        return locationCode;
    }

    public void setLocationCode(String locationCode) {
        this.locationCode = locationCode;
    }

    public String getMatchCode() {
        return matchCode;
    }

    public void setMatchCode(String matchCode) {
        this.matchCode = matchCode;
    }

	public String getPrecisionLevel() {
		return precisionLevel;
	}

	public void setPrecisionLevel(String precisionLevel) {
		this.precisionLevel = precisionLevel;
	}
}
