/*******************************************************************************
 * Copyright 2016 Pitney Bowes Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License.
 *   You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an
 *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  
 *  See the License for the specific language governing permissions and limitations under the License.
 *******************************************************************************/
package com.pb.locationintelligence.geocode;

public enum Countries 
{
	AMERICAN_SAMOA,
	ANDORRA,
	ANGOLA,
	ARGENTINA,
	ARUBA,
	AUSTRALIA,
	AUSTRIA,
	BAHAMAS,
	BAHRAIN,
	BARBADOS,
	BELGIUM,
	BELIZE,
	BENIN,
	BERMUDA,
	BOLIVIA,
	BOTSWANA,
	BRAZIL,
	BURKINA_FASO,
	BURUNDI,
	CAMEROON,
	CANADA,
	CHILE,
	CHINA,
	CONGO,
	DEMOCRATIC_REPUBLIC_OF_CONGO,
	COSTA_RICA,
	CROATIA,
	CUBA,
	CZECH_REPUBLIC,
	DENMARK,
	DOMINICAN_REPUBLIC,
	ECUADOR,
	EGYPT,
	EL_SALVADOR,
	ESTONIA,
	FINLAND,
	FRANCE,
	FRENCH_GUYANA,
	GABON,
	GERMANY,
	GHANA,
	GREAT_BRITAIN,
	GREECE,
	GUADELOUPE,
	GUAM,
	GUATEMALA,
	GUYANA,
	HONDURAS,
	HONG_KONG,
	HUNGARY,
	ICELAND,
	INDIA,
	INDONESIA,
	IRELAND,
	ITALY,
	JAMAICA,
	JAPAN,
	KENYA,
	KUWAIT,
	LATVIA,
	LEBANON,
	LESOTHO,
	LIECHTENSTEIN,
	LITHUANIA,
	LUXEMBOURG,
	MACAO,
	MALAWI,
	MALAYSIA,
	MALI,
	MARTINIQUE,
	MAURITANIA,
	MAURITIUS,
	MAYOTTE,
	MEXICO,
	MONACO,
	MOROCCO,
	MOZAMBIQUE,
	NAMIBIA,
	NETHERLANDS,
	NEW_ZEALAND,
	NICARAGUA,
	NIGER,
	NIGERIA,
	NORTH_MARIANA_ISLANDS,
	NORWAY,
	OMAN,
	PALAU,
	PANAMA,
	PARAGUAY,
	PERU,
	PHILIPPINES,
	POLAND,
	PORTUGAL,
	PUERTO_RICO,
	QATAR,
	REUNION,
	ROMANIA,
	RUSSIAN_FEDERATION,
	RWANDA,
	SAINT_KITTS_AND_NEVIS,
	SAUDI_ARABIA,
	SENEGAL,
	SINGAPORE,
	SLOVAKIA,
	SLOVENIA,
	SOUTH_AFRICA,
	SPAIN,
	SURINAME,
	SWAZILAND,
	SWEDEN,
	SWITZERLAND,
	TAIWAN,
	UNITED_REPUBLIC_OF_TANZANIA,
	THAILAND,
	TOGO,
	TRINIDAD_AND_TOBAGO,
	TUNISIA,
	TURKEY,
	UGANDA,
	UKRAINE,
	UNITED_ARAB_EMIRATES,
	UNITED_KINGDOM,
	UNITED_STATES,
	URUGUAY,
	VENEZUELA,
	VIRGIN_ISLANDS,
	WORLD_GEOCODER,
	ZAMBIA,
	ZIMBABWE;

	
	public String value() 
	{
        return name();
    }

    public static Countries fromValue(String v) 
    {
        return valueOf(v);
    }
}
