/*******************************************************************************
 * Copyright 2016 Pitney Bowes Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License.
 *   You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an
 *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  
 *  See the License for the specific language governing permissions and limitations under the License.
 *******************************************************************************/
package com.pb.locationintelligence.geocode.model;

import java.util.List;
import com.pb.locationintelligence.geocode.model.forward.Address;

public class Candidate {

	/**
	 * A code describing the precision of the geocode. One of the following:
	 *	0: No coordinate information is available for this candidate address.
	 *	1: Interpolated street address.
		2:	Street segment midpoint.
		3:	Postal code 1 centroid.
		4:	Partial postal code 2 centroid.
		5:	Postal code 2 centroid.
		6:	Intersection.
		7:	Point of interest. (If database contains POI data.)
		8:	State/province centroid.
		9:	County centroid.
		10:	City centroid.
		11:	Locality centroid.
		12-15:	Reserved for unspecified custom items.
		16:	The result is an address point.
		17:	The result was generated by using address point data to modify the candidate's segment data.
		18:	The result is an address point that was projected using the centerline offset feature. You must have both a point and a street range database to use the centerline offset feature.
	 * 
	 */
	protected int precisionLevel;
	
	/**
	 * The formatted main address line.
	 */
	protected String formattedStreetAddress;
	
	/**
	 * The formatted Location  Address.
	 */
	protected String formattedLocationAddress;
	
	/**
	 * For street- or point-level candidates, this is usually the segment ID.s
	 */
	protected String identifier;
	
	/**
	 * A code describing the precision of the geocode.
	 */
	protected String precisionCode;
	
	/**
	 * Identifies the dictionary that is the source for the candidate information and data. 
	 * The source dictionary is a 0-based integer value that indicates which configured dictionary the candidate came from.
	 * If you only have a single dictionary this will always be "0".
	 */
	protected String sourceDictionary;
	protected FieldsMatching matching;
	protected GeoPos geometry;
	protected Address address;
	protected List<CandidateRange> ranges;

	public int getPrecisionLevel() {
		return precisionLevel;
	}

	public void setPrecisionLevel(int precisionLevel) {
		this.precisionLevel = precisionLevel;
	}

	public String getFormattedStreetAddress() {
		return formattedStreetAddress;
	}

	public void setFormattedStreetAddress(String formattedStreetAddress) {
		this.formattedStreetAddress = formattedStreetAddress;
	}

	public String getFormattedLocationAddress() {
		return formattedLocationAddress;
	}

	public void setFormattedLocationAddress(String formattedLocationAddress) {
		this.formattedLocationAddress = formattedLocationAddress;
	}

	public String getIdentifier() {
		return identifier;
	}

	public void setIdentifier(String identifier) {
		this.identifier = identifier;
	}

	public String getPrecisionCode() {
		return precisionCode;
	}

	public void setPrecisionCode(String precisionCode) {
		this.precisionCode = precisionCode;
	}

	public String getSourceDictionary() {
		return sourceDictionary;
	}

	public void setSourceDictionary(String sourceDictionary) {
		this.sourceDictionary = sourceDictionary;
	}

	public FieldsMatching getMatching() {
		return matching;
	}

	public void setMatching(FieldsMatching matching) {
		this.matching = matching;
	}

	public GeoPos getGeometry() {
		return geometry;
	}

	public void setGeometry(GeoPos geometry) {
		this.geometry = geometry;
	}

	public Address getAddress() {
		return address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	public List<CandidateRange> getRanges() {
		return ranges;
	}

}