/**
 * Location Intelligence APIs
 * Incorporate our extensive geodata into everyday applications, business processes and workflows.
 *
 * OpenAPI spec version: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package pb.locationintelligence.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import pb.locationintelligence.model.Boundaries;
import pb.locationintelligence.model.DemographicsThemes;


/**
 * Demographics
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-13T02:57:26.849+05:30")
public class Demographics   {
  @SerializedName("boundaries")
  private Boundaries boundaries = null;

  @SerializedName("themes")
  private DemographicsThemes themes = null;

  public Demographics boundaries(Boundaries boundaries) {
    this.boundaries = boundaries;
    return this;
  }

   /**
   * Get boundaries
   * @return boundaries
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Boundaries getBoundaries() {
    return boundaries;
  }

  public void setBoundaries(Boundaries boundaries) {
    this.boundaries = boundaries;
  }

  public Demographics themes(DemographicsThemes themes) {
    this.themes = themes;
    return this;
  }

   /**
   * Get themes
   * @return themes
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public DemographicsThemes getThemes() {
    return themes;
  }

  public void setThemes(DemographicsThemes themes) {
    this.themes = themes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Demographics demographics = (Demographics) o;
    return Objects.equals(this.boundaries, demographics.boundaries) &&
        Objects.equals(this.themes, demographics.themes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(boundaries, themes);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Demographics {\n");
    
    sb.append("    boundaries: ").append(toIndentedString(boundaries)).append("\n");
    sb.append("    themes: ").append(toIndentedString(themes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

