/**
 * Location Intelligence APIs
 * Incorporate our extensive geodata into everyday applications, business processes and workflows.
 *
 * OpenAPI spec version: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package pb.locationintelligence.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * RiskPreferences
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-13T02:57:26.849+05:30")
public class RiskPreferences   {
  @SerializedName("includeGeometry")
  private String includeGeometry = null;

  @SerializedName("includeZoneDesc")
  private String includeZoneDesc = null;

  public RiskPreferences includeGeometry(String includeGeometry) {
    this.includeGeometry = includeGeometry;
    return this;
  }

   /**
   * Get includeGeometry
   * @return includeGeometry
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getIncludeGeometry() {
    return includeGeometry;
  }

  public void setIncludeGeometry(String includeGeometry) {
    this.includeGeometry = includeGeometry;
  }

  public RiskPreferences includeZoneDesc(String includeZoneDesc) {
    this.includeZoneDesc = includeZoneDesc;
    return this;
  }

   /**
   * Get includeZoneDesc
   * @return includeZoneDesc
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getIncludeZoneDesc() {
    return includeZoneDesc;
  }

  public void setIncludeZoneDesc(String includeZoneDesc) {
    this.includeZoneDesc = includeZoneDesc;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RiskPreferences riskPreferences = (RiskPreferences) o;
    return Objects.equals(this.includeGeometry, riskPreferences.includeGeometry) &&
        Objects.equals(this.includeZoneDesc, riskPreferences.includeZoneDesc);
  }

  @Override
  public int hashCode() {
    return Objects.hash(includeGeometry, includeZoneDesc);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RiskPreferences {\n");
    
    sb.append("    includeGeometry: ").append(toIndentedString(includeGeometry)).append("\n");
    sb.append("    includeZoneDesc: ").append(toIndentedString(includeZoneDesc)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

